/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotransversal.Vistas;

/**
 *
 * @author alumno
 */
public class Aplicacion extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMMenuPrincipal = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMSubMenu1 = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMSubMenu2 = new javax.swing.JMenuItem();
        jMDescripcion = new javax.swing.JMenu();
        jMSubMenu3 = new javax.swing.JMenuItem();
        jMSubMenu4 = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMSubMenu5 = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMMenuPrincipal.setName(""); // NOI18N

        jMAlumno.setText("Alumno");

        jMSubMenu1.setText("Formulario de Alumno");
        jMAlumno.add(jMSubMenu1);

        jMMenuPrincipal.add(jMAlumno);

        jMMateria.setText("Materia");

        jMSubMenu2.setText("Formulario de Materia");
        jMMateria.add(jMSubMenu2);

        jMMenuPrincipal.add(jMMateria);

        jMDescripcion.setText("Administracion");

        jMSubMenu3.setText("Manejo de Inscripciones");
        jMDescripcion.add(jMSubMenu3);

        jMSubMenu4.setText("Manipulacion de Notas");
        jMDescripcion.add(jMSubMenu4);

        jMMenuPrincipal.add(jMDescripcion);

        jMConsultas.setText("Consultas");

        jMSubMenu5.setText("Alumnos por Materias");
        jMConsultas.add(jMSubMenu5);

        jMMenuPrincipal.add(jMConsultas);

        jMSalir.setText("Salir");
        jMMenuPrincipal.add(jMSalir);

        setJMenuBar(jMMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenu jMDescripcion;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenuBar jMMenuPrincipal;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuItem jMSubMenu1;
    private javax.swing.JMenuItem jMSubMenu2;
    private javax.swing.JMenuItem jMSubMenu3;
    private javax.swing.JMenuItem jMSubMenu4;
    private javax.swing.JMenuItem jMSubMenu5;
    // End of variables declaration//GEN-END:variables
}
