/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectotransversal.Vistas;

import javax.swing.JOptionPane;
import proyectotransversal.AccesoDatos.MateriaData;
import proyectotransversal.Entidades.Materia;

/**
 *
 * @author alumno
 */
public class MateriaView extends javax.swing.JInternalFrame {
     MateriaData md;
     Materia m;
     
    /** Creates new form Materia */
    public MateriaView() {
        initComponents();
        this.setLocation(130, 30);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtAño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrbEstado = new javax.swing.JRadioButton();
        jbAgregar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 102));
        setClosable(true);
        setTitle("Materia");
        setMinimumSize(new java.awt.Dimension(503, 467));
        setPreferredSize(new java.awt.Dimension(503, 467));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Materia");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo:");

        jbBuscar.setBackground(new java.awt.Color(0, 153, 102));
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Año:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estado:");

        jrbEstado.setBorder(null);

        jbAgregar.setBackground(new java.awt.Color(0, 153, 102));
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbEditar.setBackground(new java.awt.Color(0, 153, 102));
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbEliminar.setBackground(new java.awt.Color(0, 153, 102));
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(0, 153, 102));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalir)
                        .addContainerGap(151, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNombre)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbEstado)
                                            .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtCodigo)
                                .addGap(37, 37, 37)
                                .addComponent(jbBuscar)))
                        .addGap(72, 72, 72))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrbEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbEditar)
                    .addComponent(jbEliminar)
                    .addComponent(jbSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        md= new MateriaData();
        try{
            m= md.buscarMateria(Integer.parseInt(jtCodigo.getText()));
                if(m!=null){
                    jtCodigo.setEnabled(false);
                    jtNombre.setText(m.getNombre());
                    jtAño.setText(String.valueOf(m.getAño()));
                    jrbEstado.setSelected(m.isEstado());
                    jbAgregar.setEnabled(false);
                    jbEditar.setEnabled(true);
                    jbEliminar.setEnabled(true);
                }else{
                    jtCodigo.setEnabled(false);
                    jtCodigo.setText("");
                    jtNombre.setText("");
                    jtAño.setText("");
                    jrbEstado.setSelected(false);
                    JOptionPane.showMessageDialog(null, "Complete los campos para la nueva materia \n Dejando campo Codigo Vacio");
                    jbAgregar.setEnabled(true);
                    jbEditar.setEnabled(false);
                    jbEliminar.setEnabled(false);
                    jtNombre.requestFocus();
                }
            }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Ingrese un Numero para Codigo "+e.getMessage());
                    jtCodigo.setText("");
                    jtCodigo.requestFocus();
            }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        md = new MateriaData();
        m= new Materia();
            
        try{
            if (jtNombre.getText().isEmpty()){
                            jtNombre.requestFocus();
                    }else{

                            if (comprobarCaracteres(jtNombre.getText())){
                            m.setNombre(jtNombre.getText());
                            }else{
                            JOptionPane.showMessageDialog(null, "Debe Ingresar solo letras para Nombre");
                            jtNombre.setText("");
                            jtNombre.requestFocus();
                            return;
                            }
                    }
        m.setAño(Integer.parseInt(jtAño.getText()));
        m.setEstado(jrbEstado.isSelected());
        md.guardarMateria(m);
        jtCodigo.setEnabled(true);
        int codigo = m.getIdMateria();
        JOptionPane.showMessageDialog(null, "Se creo la  nueva Materia con Id: "+codigo);
        jtCodigo.setText(String.valueOf(m.getIdMateria()));
        jbAgregar.setEnabled(false);
        jbEditar.setEnabled(true);
        jbEliminar.setEnabled(true);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingrese un Numero para Año "+e.getMessage());
            jtAño.setText("");
            jtAño.requestFocus();
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        md=new MateriaData();
        m=new Materia();
        try{
       m.setIdMateria(Integer.parseInt(jtCodigo.getText()));
       
       if (jtNombre.getText().isEmpty()){
                            jtNombre.requestFocus();
                    }else{

                            if (comprobarCaracteres(jtNombre.getText())){
                            m.setNombre(jtNombre.getText());
                            }else{
                            JOptionPane.showMessageDialog(null, "Debe Ingresar solo letras para Nombre");
                            jtNombre.setText("");
                            jtNombre.requestFocus();
                            return;
                            }
                    }
       m.setAño(Integer.parseInt(jtAño.getText()));
       m.setEstado(jrbEstado.isSelected());
       md.modificarMateria(m);
       jtCodigo.setText("");
       jtNombre.setText("");
       jtAño.setText("");
       jrbEstado.setSelected(false);
       jbAgregar.setEnabled(true);
       jtCodigo.setEnabled(true);
        }catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null, "Corrobore los datos ingresados "+e.getMessage());
             jtAño.setText("");
             jtAño.requestFocus();
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        md= new MateriaData();
        try{
            md.eliminarMateria(Integer.parseInt(jtCodigo.getText()));
            jtCodigo.setText("");
            jtNombre.setText("");
            jtAño.setText("");
            jrbEstado.setSelected(false);
            jtCodigo.setEnabled(true);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingrese un Numero para Año "+e.getMessage());
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private boolean comprobarCaracteres(String e){
        int longitud = e.length();
        boolean validado=true;
        for (int i =0; i<longitud;i++){
            char c = e.charAt(i);
            if (!Character.isLetter(c) && !Character.isWhitespace(c)){
                validado=  false;
            }
        }
        return validado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtAño;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables

}
